global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mem0_api'
    static_configs:
      - targets: ['mem0_prometheus_exporter:9093']
    scrape_interval: 15s

  - job_name: 'ollama_instances'
    static_configs:
      - targets: ['mem0_ollama_exporter:9092']
    scrape_interval: 15s
